spring:
  application:
    name: order-service
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/order-service} # Default value if DB_URL is not set
    username: ${DB_USERNAME:root} # Default value if DB_USERNAME is not set
    password: ${DB_PASSWORD:root} # Default value if DB_PASSWORD is not set
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${SERVER_PORT:8182}
